[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {
		\ 'colorscheme': 'wombat'
		\ }
	
	" # show statusbar
	set laststatus=2
	" # hide --INSERT--
	set noshowmode
'''

[[plugins]]
repo = 'Shougo/neocomplete'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'cohama/lexima.vim'
